.simitall_require_phenotype_backend <- function(package, feature) {
  if (!requireNamespace(package, quietly = TRUE)) {
    stop(
      "Package '", package, "' is required for ", feature, ". ",
      "Install the population dependency profile or run install.packages('",
      package, "').",
      call. = FALSE
    )
  }
}

.simitall_phenotype_records <- function(data) {
  if (is.character(data) && length(data) == 1L) {
    if (!file.exists(data)) stop("Phenotype input file does not exist: ", data)
    data <- utils::read.delim(
      data,
      check.names = FALSE,
      stringsAsFactors = FALSE
    )
  }
  if (!is.data.frame(data)) {
    stop("data must be a data frame or a path to a tab-separated file")
  }
  if (!nrow(data)) stop("data must contain at least one record")
  as.data.frame(data, check.names = FALSE, stringsAsFactors = FALSE)
}

.simitall_write_optional_table <- function(data, out_file) {
  if (is.null(out_file)) return(invisible(NULL))
  if (!is.character(out_file) || length(out_file) != 1L || !nzchar(out_file)) {
    stop("out_file must be NULL or one non-empty file path")
  }
  dir.create(dirname(out_file), recursive = TRUE, showWarnings = FALSE)
  utils::write.table(
    data,
    out_file,
    sep = "\t",
    quote = FALSE,
    row.names = FALSE
  )
  invisible(normalizePath(out_file, mustWork = FALSE))
}

.simitall_validate_simstudy_name <- function(name, argument) {
  if (!is.character(name) || length(name) != 1L || !nzchar(name)) {
    stop(argument, " must be one non-empty column name")
  }
  name
}

#' Simulate shared breeding-family effects with simstudy
#'
#' Draw one normally distributed random effect for every observed family and
#' attach that same value to all records belonging to the family. Random
#' effects are generated by simstudy; simitall only validates identifiers and
#' joins the package-generated values back to the breeding records.
#'
#' @param data Data frame or tab-separated file containing breeding records.
#' @param family_id Name of the column identifying breeding families.
#' @param variance Non-negative variance of the family random effect.
#' @param effect_name Name of the generated effect column.
#' @param out_file Optional output TSV path. When NULL, no file is written.
#' @param seed Integer random-number seed passed to the package simulation.
#'
#' @return A data frame containing the original records and family effect.
#' @examples
#' \dontrun{
#' families <- data.frame(
#'   sample = paste0("line", 1:6),
#'   family = rep(c("fam1", "fam2"), each = 3)
#' )
#' families <- simulate_family_effects(
#'   families,
#'   family_id = "family",
#'   variance = 0.2
#' )
#' }
#' @export
simulate_family_effects <- function(
    data,
    family_id = "family",
    variance = 1,
    effect_name = "family_effect",
    out_file = NULL,
    seed = 1L) {
  .simitall_require_phenotype_backend("simstudy", "family-effect simulation")
  .simitall_require_phenotype_backend("data.table", "family-effect simulation")
  records <- .simitall_phenotype_records(data)
  family_id <- .simitall_validate_simstudy_name(family_id, "family_id")
  effect_name <- .simitall_validate_simstudy_name(effect_name, "effect_name")
  if (!family_id %in% names(records)) {
    stop("family_id column not found: ", family_id)
  }
  if (effect_name %in% names(records)) {
    stop("effect_name already exists in data: ", effect_name)
  }
  if (length(variance) != 1L || !is.finite(variance) || variance < 0) {
    stop("variance must be one non-negative number")
  }
  family_key <- as.character(records[[family_id]])
  if (anyNA(family_key) || any(!nzchar(family_key))) {
    stop("family identifiers cannot be missing or empty")
  }

  set.seed(as.integer(seed))
  family_levels <- data.frame(
    .simitall_family_key = unique(family_key),
    stringsAsFactors = FALSE
  )
  definition <- simstudy::defDataAdd(
    varname = effect_name,
    formula = 0,
    variance = variance,
    dist = "normal"
  )
  generated <- simstudy::addColumns(
    definition,
    data.table::as.data.table(family_levels)
  )
  records[[effect_name]] <- generated[[effect_name]][
    match(family_key, generated$.simitall_family_key)
  ]
  .simitall_write_optional_table(records, out_file)
  records
}

#' Simulate an ordinal breeding trait with simstudy
#'
#' Generate an ordered categorical outcome using simstudy::genOrdCat().
#' A numeric predictor can contain genotype scores, package-generated family
#' effects, environmental effects, or any combination prepared by the user.
#'
#' @param data Data frame or tab-separated file containing one row per sample.
#' @param predictor Numeric predictor column used to shift category
#'   probabilities. Use NULL for unadjusted base probabilities.
#' @param probabilities Category probabilities, ordered from the lowest to the
#'   highest category. Values must sum to one.
#' @param trait_name Name of the generated ordinal-trait column.
#' @param labels Optional labels for the ordered categories.
#' @param id Name of a unique sample-ID column. When NULL, a temporary ID is
#'   generated and removed before returning.
#' @param out_file Optional output TSV path. When NULL, no file is written.
#' @param seed Integer random-number seed passed to the package simulation.
#'
#' @return A data frame containing the original records and an ordered factor.
#' @examples
#' \dontrun{
#' records <- data.frame(
#'   sample = paste0("line", 1:100),
#'   genetic_score = stats::rnorm(100)
#' )
#' ordinal <- simulate_ordinal_trait(
#'   records,
#'   predictor = "genetic_score",
#'   probabilities = c(0.1, 0.3, 0.4, 0.2),
#'   labels = c("resistant", "mild", "moderate", "severe")
#' )
#' }
#' @export
simulate_ordinal_trait <- function(
    data,
    predictor = "genetic_score",
    probabilities = c(0.25, 0.25, 0.25, 0.25),
    trait_name = "ordinal_trait",
    labels = NULL,
    id = "sample",
    out_file = NULL,
    seed = 1L) {
  .simitall_require_phenotype_backend("simstudy", "ordinal-trait simulation")
  .simitall_require_phenotype_backend("data.table", "ordinal-trait simulation")
  records <- .simitall_phenotype_records(data)
  trait_name <- .simitall_validate_simstudy_name(trait_name, "trait_name")
  if (trait_name %in% names(records)) {
    stop("trait_name already exists in data: ", trait_name)
  }
  if (!is.numeric(probabilities) || length(probabilities) < 2L ||
      any(!is.finite(probabilities)) || any(probabilities < 0) ||
      abs(sum(probabilities) - 1) > 1e-8) {
    stop(
      "probabilities must contain at least two non-negative values ",
      "summing to one"
    )
  }
  if (!is.null(labels) && length(labels) != length(probabilities)) {
    stop("labels must have one value per ordinal category")
  }
  if (!is.null(predictor)) {
    predictor <- .simitall_validate_simstudy_name(predictor, "predictor")
    if (!predictor %in% names(records)) {
      stop("predictor column not found: ", predictor)
    }
    if (!is.numeric(records[[predictor]]) ||
        any(!is.finite(records[[predictor]]))) {
      stop("predictor must identify a finite numeric column")
    }
  }

  internal_id <- is.null(id)
  id_name <- if (internal_id) {
    ".simitall_sample_id"
  } else {
    .simitall_validate_simstudy_name(id, "id")
  }
  if (internal_id) {
    records[[id_name]] <- seq_len(nrow(records))
  } else {
    if (!id_name %in% names(records)) stop("id column not found: ", id_name)
    if (anyNA(records[[id_name]]) || anyDuplicated(records[[id_name]])) {
      stop("id values must be present and unique")
    }
  }
  order_name <- ".simitall_original_order"
  while (order_name %in% names(records)) order_name <- paste0(order_name, "_")
  records[[order_name]] <- seq_len(nrow(records))

  set.seed(as.integer(seed))
  table <- data.table::as.data.table(records)
  data.table::setkeyv(table, id_name)
  generated <- simstudy::genOrdCat(
    table,
    adjVar = predictor,
    baseprobs = probabilities,
    catVar = trait_name,
    asFactor = TRUE,
    idname = id_name
  )
  generated <- as.data.frame(generated, check.names = FALSE)
  generated <- generated[order(generated[[order_name]]), , drop = FALSE]
  generated[[order_name]] <- NULL
  if (internal_id) generated[[id_name]] <- NULL
  if (!is.null(labels)) {
    generated[[trait_name]] <- factor(
      generated[[trait_name]],
      levels = levels(generated[[trait_name]]),
      labels = labels,
      ordered = TRUE
    )
  } else {
    generated[[trait_name]] <- ordered(generated[[trait_name]])
  }
  rownames(generated) <- NULL
  .simitall_write_optional_table(generated, out_file)
  generated
}

#' Simulate a Poisson or negative-binomial breeding trait with simstudy
#'
#' Generate count outcomes with simstudy from a formula evaluated against the
#' supplied breeding records. The formula can include genotype scores, family
#' effects generated by simulate_family_effects(), environments, and other
#' columns.
#'
#' @param data Data frame or tab-separated file containing one row per sample.
#' @param formula Numeric intercept or simstudy formula defining the expected
#'   count on the selected link scale.
#' @param distribution Count distribution: "poisson" or
#'   "negative_binomial".
#' @param dispersion Positive negative-binomial dispersion parameter. Ignored
#'   for Poisson traits.
#' @param link Link used by simstudy, usually "log".
#' @param trait_name Name of the generated count-trait column.
#' @param out_file Optional output TSV path. When NULL, no file is written.
#' @param seed Integer random-number seed passed to the package simulation.
#'
#' @return A data frame containing the original records and integer counts.
#' @examples
#' \dontrun{
#' records <- data.frame(
#'   sample = paste0("line", 1:100),
#'   genetic_score = stats::rnorm(100)
#' )
#' counts <- simulate_count_trait(
#'   records,
#'   formula = "1 + 0.4 * genetic_score",
#'   distribution = "negative_binomial",
#'   dispersion = 0.5
#' )
#' }
#' @export
simulate_count_trait <- function(
    data,
    formula = 1,
    distribution = c("poisson", "negative_binomial"),
    dispersion = 1,
    link = c("log", "identity"),
    trait_name = "count_trait",
    out_file = NULL,
    seed = 1L) {
  .simitall_require_phenotype_backend("simstudy", "count-trait simulation")
  .simitall_require_phenotype_backend("data.table", "count-trait simulation")
  records <- .simitall_phenotype_records(data)
  distribution <- match.arg(distribution)
  link <- match.arg(link)
  trait_name <- .simitall_validate_simstudy_name(trait_name, "trait_name")
  if (trait_name %in% names(records)) {
    stop("trait_name already exists in data: ", trait_name)
  }
  valid_formula <- (is.numeric(formula) && length(formula) == 1L &&
                    is.finite(formula)) ||
    (is.character(formula) && length(formula) == 1L && nzchar(formula))
  if (!valid_formula) {
    stop("formula must be one finite number or one non-empty character formula")
  }
  if (distribution == "negative_binomial" &&
      (length(dispersion) != 1L || !is.finite(dispersion) ||
       dispersion <= 0)) {
    stop("dispersion must be positive for a negative-binomial trait")
  }

  set.seed(as.integer(seed))
  definition <- simstudy::defDataAdd(
    varname = trait_name,
    formula = formula,
    variance = if (distribution == "negative_binomial") dispersion else 0,
    dist = if (distribution == "negative_binomial") {
      "negBinomial"
    } else {
      "poisson"
    },
    link = link
  )
  generated <- simstudy::addColumns(
    definition,
    data.table::as.data.table(records)
  )
  generated <- as.data.frame(generated, check.names = FALSE)
  rownames(generated) <- NULL
  .simitall_write_optional_table(generated, out_file)
  generated
}

#' Simulate direct and parental effects across a pedigree with pedtricks
#'
#' Wrap pedtricks::phen_sim() to simulate direct, maternal, and paternal
#' genetic or environmental effects over an arbitrary pedigree. Covariance
#' matrices and the package's "d", "m", and "p" effect codes are passed through
#' unchanged, and all package-generated truth components can be retained.
#'
#' @param pedigree Data frame or TSV containing individual, sire, and dam IDs.
#' @param id,sire,dam Column names in pedigree.
#' @param traits Positive number of simulated traits.
#' @param genetic_covariance Covariance matrix for direct and parental genetic
#'   effects. The matrix dimension must equal length(parental_genetic).
#' @param environmental_covariance Covariance matrix for direct and parental
#'   environmental effects.
#' @param parental_genetic Effect codes for genetic_covariance: "d" (direct),
#'   "m" (maternal), or "p" (paternal).
#' @param parental_environmental Effect codes for environmental_covariance.
#' @param sampled Optional vector identifying sampled pedigree members, passed
#'   to pedtricks::phen_sim().
#' @param records Optional phenotype-availability specification passed to
#'   pedtricks::phen_sim().
#' @param return_all_effects Retain direct and parental truth components.
#' @param out_prefix Optional output prefix. Writes .phenotypes.tsv,
#'   .effects.tsv when available, and .summary.json.
#' @param seed Integer random-number seed passed to the package simulation.
#' @param verbose Show messages from pedtricks.
#'
#' @return The result returned by pedtricks::phen_sim(), optionally with a
#'   named paths element for written outputs.
#' @examples
#' \dontrun{
#' pedigree <- data.frame(
#'   id = c("dam1", "sire1", "child1", "child2"),
#'   sire = c(NA, NA, "sire1", "sire1"),
#'   dam = c(NA, NA, "dam1", "dam1")
#' )
#' parental <- simulate_parental_effects(
#'   pedigree,
#'   genetic_covariance = diag(c(1, 0.3)),
#'   environmental_covariance = diag(c(0.8, 0.2)),
#'   parental_genetic = c("d", "m"),
#'   parental_environmental = c("d", "m")
#' )
#' }
#' @export
simulate_parental_effects <- function(
    pedigree,
    id = "id",
    sire = "sire",
    dam = "dam",
    traits = 1L,
    genetic_covariance = diag(c(1, 0.25)),
    environmental_covariance = diag(c(1, 0.25)),
    parental_genetic = c("d", "m"),
    parental_environmental = c("d", "m"),
    sampled = NULL,
    records = NULL,
    return_all_effects = TRUE,
    out_prefix = NULL,
    seed = 1L,
    verbose = FALSE) {
  .simitall_require_phenotype_backend(
    "pedtricks",
    "parental-effect simulation"
  )
  source_pedigree <- .simitall_phenotype_records(pedigree)
  columns <- c(id, sire, dam)
  if (any(!columns %in% names(source_pedigree))) {
    stop("pedigree must contain the requested id, sire, and dam columns")
  }
  pedigree <- data.frame(
    id = as.character(source_pedigree[[id]]),
    sire = as.character(source_pedigree[[sire]]),
    dam = as.character(source_pedigree[[dam]]),
    stringsAsFactors = FALSE
  )
  if (anyNA(pedigree$id) || any(!nzchar(pedigree$id)) ||
      anyDuplicated(pedigree$id)) {
    stop("pedigree individual IDs must be present and unique")
  }
  known_parents <- unique(c(pedigree$sire, pedigree$dam))
  known_parents <- known_parents[
    !is.na(known_parents) & nzchar(known_parents)
  ]
  missing_parents <- setdiff(known_parents, pedigree$id)
  if (length(missing_parents)) {
    stop(
      "All non-missing parents must occur in the pedigree: ",
      paste(missing_parents, collapse = ", ")
    )
  }
  if (length(traits) != 1L || !is.finite(traits) || traits < 1L ||
      traits != as.integer(traits)) {
    stop("traits must be a positive integer")
  }
  traits <- as.integer(traits)

  validate_effect_model <- function(covariance, codes, label) {
    if (!is.matrix(covariance) || !is.numeric(covariance) ||
        nrow(covariance) != ncol(covariance) ||
        nrow(covariance) != length(codes) ||
        any(!is.finite(covariance))) {
      stop(
        label,
        " covariance must be a finite square matrix matching its effect codes"
      )
    }
    if (length(codes) %% traits != 0L ||
        any(!codes %in% c("d", "m", "p"))) {
      stop(
        label,
        " effect codes must use d, m, or p with a length divisible by traits"
      )
    }
    invisible(TRUE)
  }
  validate_effect_model(genetic_covariance, parental_genetic, "genetic")
  validate_effect_model(
    environmental_covariance,
    parental_environmental,
    "environmental"
  )

  set.seed(as.integer(seed))
  result <- pedtricks::phen_sim(
    pedigree = pedigree,
    traits = traits,
    randomA = genetic_covariance,
    randomE = environmental_covariance,
    parentalA = parental_genetic,
    parentalE = parental_environmental,
    sampled = sampled,
    records = records,
    returnAllEffects = return_all_effects,
    verbose = verbose
  )

  if (!is.null(out_prefix)) {
    if (!is.character(out_prefix) || length(out_prefix) != 1L ||
        !nzchar(out_prefix)) {
      stop("out_prefix must be NULL or one non-empty path prefix")
    }
    paths <- list(
      phenotypes = paste0(out_prefix, ".phenotypes.tsv"),
      summary = paste0(out_prefix, ".summary.json")
    )
    .simitall_write_optional_table(result$phenotypes, paths$phenotypes)
    if (!is.null(result$allEffects)) {
      paths$effects <- paste0(out_prefix, ".effects.tsv")
      .simitall_write_optional_table(result$allEffects, paths$effects)
    }
    summary <- list(
      backend = "pedtricks",
      backend_version = as.character(utils::packageVersion("pedtricks")),
      seed = as.integer(seed),
      traits = traits,
      individuals = nrow(pedigree),
      parental_genetic = parental_genetic,
      parental_environmental = parental_environmental,
      return_all_effects = isTRUE(return_all_effects)
    )
    dir.create(dirname(paths$summary), recursive = TRUE, showWarnings = FALSE)
    jsonlite::write_json(
      summary,
      paths$summary,
      pretty = TRUE,
      auto_unbox = TRUE
    )
    result$paths <- paths
  }
  result
}
